# Generated by Django 4.2.25 on 2025-11-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('authentication', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecode',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_codes', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursecode',
            name='name',
            field=models.CharField(help_text='Override name if not using a course', max_length=100),
        ),
    ]
