# Generated by Django 4.2.25 on 2025-11-11 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Classroom name (e.g., Freesia Bloom, Bluebells Bloom)', max_length=100, unique=True)),
                ('batch_number', models.PositiveIntegerField(blank=True, help_text='Batch number if applicable', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['name', '-batch_number'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('alumni', 'Alumni'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='AlumniJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, help_text='Current job title or position', max_length=200, null=True)),
                ('employer', models.CharField(blank=True, help_text='Company or organization name', max_length=200, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly salary', max_digits=10, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('looking', 'Looking for Job'), ('continuing_studies', 'Continuing Studies'), ('not_working', 'Not Working'), ('married', 'Married'), ('settled', 'Settled')], max_length=30, null=True)),
                ('job_before_bloom', models.CharField(blank=True, help_text='Job or status before joining Bloom program', max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Job start date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about employment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'status': 'alumni'}, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_job', to='students.student')),
            ],
            options={
                'verbose_name': 'Alumni Job',
                'verbose_name_plural': 'Alumni Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Classroom/Batch this student belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.classroom'),
        ),
    ]
