# Generated by Django 4.2.25 on 2025-11-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_classroom_alter_student_status_alumnijob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(help_text='Classroom name (e.g., Freesia Bloom, Bluebells Bloom)', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'batch_number')},
        ),
    ]
