# Generated by Django 4.2.25 on 2025-11-13 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_alter_classroom_name_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Teachers assigned to this classroom', related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
