# Generated by Django 4.2.25 on 2025-11-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_classroom_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_job',
            field=models.CharField(blank=True, help_text='Current job title or position', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='job_before_bloom',
            field=models.CharField(blank=True, help_text='Job or status before joining Bloom program', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly salary', max_digits=10, null=True),
        ),
    ]
