# Generated by Django 4.2.25 on 2025-10-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('attendance', 'Attendance Report'), ('progress', 'Progress Report'), ('enrollment', 'Enrollment Report'), ('completion', 'Completion Report'), ('custom', 'Custom Report')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_type', models.CharField(choices=[('attendance', 'Attendance Report'), ('progress', 'Progress Report'), ('enrollment', 'Enrollment Report'), ('completion', 'Completion Report'), ('custom', 'Custom Report')], max_length=20)),
                ('template_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
